Models
it-muslim/QuranWords pull request #3
Opened 2018-10-14 20:59 UTC by govza

Models for Reciter and Recitations.

2018-10-17 06:31 UTC, al-muammar requested changes
1. Move the refactoring part and moving to `backend` into a separate PR
2. Move the testing part into a separate PR
3. Write a better description, mention how your data is structured, otherwise, it is difficult to review the PR
4. Give a more descriptive title to your PR. What models? What is happening with them?

2018-10-17 06:31 UTC, al-muammar commented on .travis.yml
> +sudo: required
It isn't connected with this PR in any way. Please, move it to a separate PR.

2018-10-17 06:31 UTC, al-muammar commented on backend/Dockerfile
> +RUN pip3 install -r testing.txt
Why did you decide to rename it?

2018-10-17 06:31 UTC, al-muammar commented on backend/quran/models.py
> +    '''General information about Surahs'''
```
    """Model representing a surah from the Qur’an."""
```

2018-10-17 06:31 UTC, al-muammar commented on backend/quran/migrations/0001_initial.py
> +# Generated by Django 2.1 on 2018-10-14 20:00
Apply formatting to this file.

2018-10-17 06:31 UTC, al-muammar commented on backend/quran/models.py
> +    quality = models.CharField(max_length=50, blank=True)
Make it a choice filed, decrease the number of characters.
What does the quality signify?

2018-10-17 06:31 UTC, al-muammar commented on backend/pytest.ini
> +[pytest]
Move pytest into another PR.

2018-10-17 06:31 UTC, al-muammar commented on backend/quran/models.py
> +class Reciter(models.Model):
I can't see `speed` option. A reciter could recite slowly or quickly. We might add it here.

2018-10-17 06:31 UTC, al-muammar commented on backend/quran/models.py
> +    description = models.CharField(max_length=255, blank=True)
What is a use-case for `description`? Can't this information be decoded in other fields?

2018-10-17 06:31 UTC, al-muammar commented on backend/quran/tests.py
> +class TestSimple:
Move it into a separate diff.

2018-10-17 06:31 UTC, al-muammar commented on backend/testing.txt
> +-r requirements.txt
Move it to another PR.

2018-10-17 06:31 UTC, al-muammar commented on docker-compose-dev.yml
> +version: "3"
Move it to a separate PR.

2018-10-17 06:31 UTC, al-muammar commented on docker-compose.yml
> +  backend:
To another PR.

2018-10-17 06:31 UTC, al-muammar commented on backend/quran/migrations/0002_load_data.py
> +def unload_recitations(apps, schema_editor):
You have 4 `unload_*` functions, but they are doing the same work. Merge it into one function.

2018-10-17 06:31 UTC, al-muammar commented on backend/config/testing.py
> +from .settings import *
Move it to a separate PR.

2018-10-17 06:31 UTC, Jihadik commented on backend/helpers/recitation/convert_recitation_csv.py
> +'''Convert recit-segments.csv to django fixtures file'''
There is no word `recit` in English.

2018-10-17 06:31 UTC, Jihadik commented on backend/quran/migrations/0002_load_data.py
> +fixture_recitations_list = [
Why don't you put it inside the function?

2019-01-12 20:09 UTC, govza commented
Think this branch is way outdated and I have no desire to update this.
Homework: think about it and understand why.

2019-01-12 20:09 UTC, closed without merging